---
title: "Lab 06 - Functions and iterations"
author: "Maya Smaoui"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )

diamonds
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning
diamonds <- diamonds %>%
  filter(length_mm > 0, depth_mm > 0, width_mm > 0)

stats_diamonds <- cleaned_data %>%
  group_by(cut)%>%
  summarise(
    mean_length = mean(length_mm),
    mean_width = mean(length_mm),
    mean_depth = mean(depth_mm),
    mean_price_per_volume_and_carat = mean(price/(length_mm*depth_mm*width_mm*carat)),
    mean_carat = mean(carat)
  )


stats_diamonds

long_data <- diamonds %>%
  pivot_longer(cols = c(length_mm, depth_mm, width_mm), names_to = "variables", values_to = "values" )

long_data
  
  

ggplot(long_data, mapping = aes(x = carat, y = values, colour = variables)) +
  geom_point(size = 0.5) +
  geom_smooth(method = "lm", se = FALSE)

```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

mean_table <- diamonds %>%
  summarise(mean_table_mm = mean(table_mm))

mean_table_categories <- diamonds %>%
  group_by(clarity) %>%
  summarise(mean_table_mm = mean(table_mm))
  
# Overall table_mm arithmetic mean?
mean_table
mean_table_categories

mean_all_variables <- diamonds %>%
  summarise(across(where(is.numeric)), mean, .names = "avg_{.cols}")
mean_all_variables
# table_mm arithmetic mean within each clarity category






```

_There is a relationship between the clarity and the average table length: the better the quality, the lower the average table length._

```{r}
# calculate the arithmetic mean across all numeric variables




```

## Exercise 3

```{r}
# Write gmean() command



```

## Exercise 4

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)


# Create for loop to test gmean() on the above examples


```


## Exercise 5

```{r}
# Copy gmean() from Ex 3 and edit it to check the input





# Copy your code from Ex 4 to test your new command





```

## Exercise 6

```{r}
# replicate the for loop from Ex 4 using the map (or a similar) function

```


## Exercise 7

```{r}
# Overall table_mm arithmetic mean, median, and geometric mean?






# Arithmetic mean, median, and geometric mean of table_mm within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```

## Exercise 10 (optional)

_Do derivation on paper, unless you know how to write LaTeX code_
